#1
# print("Welcome to UVPCE")
#2
# name=input("Your Name: ")
# enum=int(input("Your Enrollment No.: "))
# branch=input("Branch: ")
# age=int(input("Age: "))
# email=input("Email: ")
# pnum=int(input("Mobile No: "))
# print("=============================")
# print("Your Name:",name)
# print("Your Enrollment No.:",enum)
# print("Branch:",branch)
# print("Age:",age)
# print("Email:",email)
# print("Mobile No:",pnum)
# print("=============================")
#4
# a = 10
# b = 10.5
# c = "String"
# print(type(a))
# print(type(b))
# print(type(c))
#3
# x = 12 + 3 - 4 / 2 < 3 + 13
# print(x)
# y = (10 * 2) % 2 << ++4
# print(y)
#5
# usr=input("Enter a Character: ")
# if(usr == 'a' or usr == 'A' or usr == 'e' or usr == 'E' or usr == 'i' or usr == 'I' or usr == 'o' or usr == 'O' or usr == 'u' or usr == 'U'):
#     print("Character is Vowel.")
# else:
#     print("Character is not Vowel.")
#6
# days = int(input("Enter the days of Deleyed Returning: "))
# if(days>=1 and days<=5):
#     print("40 paisa per day.")
# elif(days>=6 and days<=10):
#     print("65 paisa per day.")
# else:
#     print("80 paisa per day.")
#7
# a = int(input("Enter a First Number: "))
# b = int(input("Enter a Second Number: "))
# c = int(input("Enter a Third Number: "))
# count=0
# max_odd=0
# if(a%2!=0):
#     count +=1
#     if(a>max_odd):
#         max_odd=a
# if(b%2!=0):
#     count +=1
#     if(b>max_odd):
#         max_odd=b
# if(c%2!=0):
#     count +=1
#     if(c>max_odd):
#         max_odd=c
# print("Max Odd Number:",max_odd)
# print("Count:",count)
    
    